---
- name: Get roles from the server API and save response to YAML file
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Send GET request to the API endpoint
      ansible.builtin.uri:
        url: "https://{{ server_name }}{{ target_url }}users"
        method: GET
        user: admin
        password: "{{ my_password }}"
        force_basic_auth: true
        return_content: true  # Ensure the response content is returned
      #  headers:
      #    Authorization: "Bearer YOUR_ACCESS_TOKEN"  # If authentication is required
        validate_certs: false  # Disable cert validation if you're using self-signed certificates
      register: api_response

    - name: Show the API response (for debugging purposes)
      ansible.builtin.debug:
        var: api_response.json

    - name: Save API response to a YAML file
      ansible.builtin.copy:
        content: "{{ api_response.json.results | to_nice_yaml }}"
        dest: "/tmp/api_response.yaml"
        mode: '0644'  # Set permissions to read/write for owner, read for others
      register: my_yaml_reponse

    - name: Show the API response (for debugging purposes)
      ansible.builtin.debug:
        var: "{{ api_response.json.results | to_nice_yaml(indent=2, width=80) }}"
