---
- name: Get roles from the server API and save response to YAML file
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Send GET request to the API endpoint
      ansible.builtin.uri:
        url: "https://{{ server_name }}{{ target_url }}users"
        method: GET
        user: admin
        password: "{{ my_password }}"
        force_basic_auth: true
        return_content: true  # Ensure the response content is returned
      #  headers:
      #    Authorization: "Bearer YOUR_ACCESS_TOKEN"  # If authentication is required
        validate_certs: false  # Disable cert validation if you're using self-signed certificates
      register: api_response

    - name: Save API response to a YAML file
      ansible.builtin.copy:
        src: templates/users_to_yaml.j2
        dest: /tmp/aap_user_accounts.yaml
        mode: '0644'  # Set permissions to read/write for owner, read for others

    - name: Show the API response (for debugging purposes)
      ansible.builtin.debug:
        var: "{{ api_response.json.results | to_nice_yaml(indent=2, width=80) }}"

- name: Copy YAML output to remote server
  hosts: ec2-54-215-176-197.us-west-1.compute.amazonaws.com
  gather_facts: true
  become: true
  vars:
    repo_url: "https://github.com/rnunezrgn/RHEL_Pub.git"
    repo_dest: "/home/ec2-user/files/"
    git_token: ""
    commit_message: "Adding new AAP User collection accounts format"
    files_to_push:
      - "aap_user_accounts.yaml"

  tasks:
    - name: Copy aap_user_accounts.yaml to remote server.
      ansible.builtin.copy:
        dest: "/home/ec2-user/aap_user_accounts.yaml"
        src: "/tmp/aap_user_accounts.yaml"
        mode: '0644'

    - name: Ensure Git is installed.
      ansible.builtin.dnf:
        name: git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Clone the Git repository using git_token
      ansible.builtin.git:
        repo: "https://{{ git_token }}@{{ repo_url | regex_replace('https://', '') }}"
        dest: "{{ repo_dest }}"
        clone: yes
        update: yes
     #   version: "{{ branch }}"
    #  no_log: true

    - name: Copy aap_user_accounts.yaml to remote server.
      ansible.builtin.copy:
        dest: "/home/ec2-user/files/aap_user_accounts.yaml"
        src: "/tmp/aap_user_accounts.yaml"
        mode: '0644'
        
    - name: Make changes to files (if necessary)
      ansible.builtin.copy:
        dest: "{{ files_to_push }}"  # Replace with the file you want to create or modify
        content: "This is a new file created by Ansible"
        mode: '0644'

    - name: Commit changes to the repository
      ansible.builtin.command:
        cmd: git commit -am "{{ commit_message }}"
        chdir: "{{ repo_dest }}"
      when: ansible_facts['changed']

    - name: Push changes to the Git repository
      ansible.builtin.command:
        cmd: git push origin main #"{{ branch }}"
        chdir: "{{ repo_dest }}"
      when: ansible_facts['changed']
