---
- name: Upgrading all Modules to Latest
  hosts: rhel9k8s
  gather_facts: False

  tasks:
    - name: Upgrading all Modules to Latest
      ansible.builtin.dnf:
        name: '*'
        state: latest