---
- name: Update Ansible Controller SMC to select different GitHub branch
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "https://your-aap.example.com"
    api_user: "your_username"
    api_pass: "your_password"
    project_id: 41  # <-- Job Template ID to update
    my_branch: ""  # Branch from survey "main", "test" or "rnunez"

  tasks:
    - name: Debug the environment variable
      ansible.builtin.debug:
        msg: "Environment variable: {{ my_branch }}"

    - name: Update Job Template with new project
      ansible.builtin.uri:
        url: "{{ controller_host }}/api/controller/v2/projects/{{ project_id }}/"
        method: PATCH
        user: "{{ api_user }}"
        password: "{{ api_pass }}"
        force_basic_auth: true
        validate_certs: false
        headers:
          Content-Type: application/json
        body_format: json
        body: |
          {
            "scm_branch": "{{ my_branch }}"
          }
      register: update_result

    - name: Debug the project update results
      ansible.builtin.debug:
        msg: "Project updated successfully: {{ update_result.status }}"
