---
- name: Update Ansible Controller SMC for Job Template to select different GitHub branch
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "https://your-aap.example.com"
    api_user: "your_username"
    api_pass: "your_password"
    template_id: 41  # <-- Job Template ID to update
    environment: ""  # Branch from survey "main", "test" or "rnunez"
    project_ids: ""  # dev: 15, test: 16, qa: 17, prod: 18

  tasks:
   # - name: Set correct project ID based on environment
   #   ansible.builtin.set_fact:
   #     new_project_id: "{{ project_ids[environment] }}"

    - name: Update Job Template with new project
      ansible.builtin.uri:
        url: "{{ controller_host }}/api/v2/job_templates/{{ template_id }}/"
        method: PATCH
        user: "{{ api_user }}"
        password: "{{ api_pass }}"
        force_basic_auth: true
        validate_certs: false
        headers:
          Content-Type: application/json
        body_format: json
        body:
        #  project: "{{ new_project_id }}"
          scm_branch: "{{ environment }}"
      register: update_result

    - name: Debug the project update results
      ansible.builtin.debug:
        msg: "Project updated successfully: {{ update_result.status }}"
